---
################################################################################
#
#   ORGANIZATIONS section defines the organizations in the network
#
################################################################################
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/grets.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        OrdererEndpoints:
            - orderer1.grets.com:7050
            - orderer2.grets.com:7050
            - orderer3.grets.com:7050

    - &Government
        Name: Government
        ID: GovernmentMSP
        MSPDir: crypto-config/peerOrganizations/government.grets.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('GovernmentMSP.admin', 'GovernmentMSP.peer', 'GovernmentMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('GovernmentMSP.admin', 'GovernmentMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('GovernmentMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('GovernmentMSP.peer')"
        AnchorPeers:
            - Host: peer0.government.grets.com
              Port: 7051

    - &Bank
        Name: Bank
        ID: BankMSP
        MSPDir: crypto-config/peerOrganizations/bank.grets.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BankMSP.admin', 'BankMSP.peer', 'BankMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BankMSP.admin', 'BankMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BankMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('BankMSP.peer')"
        AnchorPeers:
            - Host: peer0.bank.grets.com
              Port: 7051

    - &Agency
        Name: Agency
        ID: AgencyMSP
        MSPDir: crypto-config/peerOrganizations/agency.grets.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AgencyMSP.admin', 'AgencyMSP.peer', 'AgencyMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AgencyMSP.admin', 'AgencyMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AgencyMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('AgencyMSP.peer')"
        AnchorPeers:
            - Host: peer0.agency.grets.com
              Port: 7051

    - &Thirdparty
        Name: Thirdparty
        ID: ThirdpartyMSP
        MSPDir: crypto-config/peerOrganizations/thirdparty.grets.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ThirdpartyMSP.admin', 'ThirdpartyMSP.peer', 'ThirdpartyMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ThirdpartyMSP.admin', 'ThirdpartyMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ThirdpartyMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ThirdpartyMSP.peer')"
        AnchorPeers:
            - Host: peer0.thirdparty.grets.com
              Port: 7051

    - &Audit
        Name: Audit
        ID: AuditMSP
        MSPDir: crypto-config/peerOrganizations/audit.grets.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AuditMSP.admin', 'AuditMSP.peer', 'AuditMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AuditMSP.admin', 'AuditMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AuditMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('AuditMSP.peer')"
        AnchorPeers:
            - Host: peer0.audit.grets.com
              Port: 7051

    - &Buyerseller
        Name: Buyerseller
        ID: BuyersellerMSP
        MSPDir: crypto-config/peerOrganizations/buyerseller.grets.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BuyersellerMSP.admin', 'BuyersellerMSP.peer', 'BuyersellerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BuyersellerMSP.admin', 'BuyersellerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BuyersellerMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('BuyersellerMSP.peer')"
        AnchorPeers:
            - Host: peer0.buyerseller.grets.com
              Port: 7051

    - &Sysadmin
        Name: Sysadmin
        ID: SysadminMSP
        MSPDir: crypto-config/peerOrganizations/sysadmin.grets.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('SysadminMSP.admin', 'SysadminMSP.peer', 'SysadminMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('SysadminMSP.admin', 'SysadminMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('SysadminMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('SysadminMSP.peer')"
        AnchorPeers:
            - Host: peer0.sysadmin.grets.com
              Port: 7051

################################################################################
#
#   CAPABILITIES
#
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#
#   APPLICATION
#
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#
#   ORDERER
#
################################################################################
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer1.grets.com:7050
        - orderer2.grets.com:7050
        - orderer3.grets.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    EtcdRaft:
        Consenters:
            - Host: orderer1.grets.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/grets.com/orderers/orderer1.grets.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/grets.com/orderers/orderer1.grets.com/tls/server.crt
            - Host: orderer2.grets.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/grets.com/orderers/orderer2.grets.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/grets.com/orderers/orderer2.grets.com/tls/server.crt
            - Host: orderer3.grets.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/grets.com/orderers/orderer3.grets.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/grets.com/orderers/orderer3.grets.com/tls/server.crt
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#
#   CHANNEL
#
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   PROFILES
#
################################################################################
Profiles:
    GretsOrdererGenesis:
        <<: *ChannelDefaults
        # Orderer节点配置
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            # 联盟配置
            GretsConsortium:
                Organizations:
                    - *Government
                    - *Bank
                    - *Agency
                    - *Thirdparty
                    - *Audit
                    - *Buyerseller
                    - *Sysadmin
    
    # 主通道 - 所有组织共享基础数据
    MainChannel:
        <<: *ChannelDefaults
        # 所属联盟
        Consortium: GretsConsortium
        # 通道组织
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Government
                - *Bank
                - *Agency
                - *Thirdparty
                - *Audit
                - *Buyerseller
                - *Sysadmin
            Capabilities:
                <<: *ApplicationCapabilities
    
    # 房产管理通道 - 房产信息登记与管理
    PropertyChannel:
        <<: *ChannelDefaults
        Consortium: GretsConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Government  # 土地管理局、不动产登记中心
                - *Bank        # 按揭贷款需查询房产信息
                - *Agency      # 房产经纪和开发商
                - *Buyerseller # 买卖双方
            Capabilities:
                <<: *ApplicationCapabilities
    
    # 交易处理通道 - 交易流程管理
    TransactionChannel:
        <<: *ChannelDefaults
        Consortium: GretsConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Government  # 交易监管
                - *Bank        # 资金处理
                - *Agency      # 交易发起
                - *Thirdparty  # 房产评估等辅助服务
                - *Buyerseller # 买卖双方
            Capabilities:
                <<: *ApplicationCapabilities
    
    # 金融服务通道 - 贷款和资金结算
    FinanceChannel:
        <<: *ChannelDefaults
        Consortium: GretsConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Government  # 税务监管
                - *Bank        # 主要金融服务提供方
                - *Buyerseller # 买卖双方（贷款申请、还款）
            Capabilities:
                <<: *ApplicationCapabilities
    
    # 审计通道 - 交易合规性审计
    AuditChannel:
        <<: *ChannelDefaults
        Consortium: GretsConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Government  # 政府监管
                - *Audit       # 审计机构
                - *Sysadmin    # 系统管理员
            Capabilities:
                <<: *ApplicationCapabilities
                
    # 系统管理通道 - 系统管理和配置
    AdminChannel:
        <<: *ChannelDefaults
        Consortium: GretsConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Government  # 政府监管
                - *Sysadmin    # 系统管理员
            Capabilities:
                <<: *ApplicationCapabilities